
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - o11y.splunk.com
  resources:
  - splunkotelagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - o11y.splunk.com
  resources:
  - splunkotelagents/finalizers
  verbs:
  - update
- apiGroups:
  - o11y.splunk.com
  resources:
  - splunkotelagents/status
  verbs:
  - get
  - patch
  - update
